### ISSUE TITLE
Connect Refused on Mac

### ISSUE THREAD

**Issue by stepro71** [CuriousDrive/BookStores#2]
Hi, I am using this with Mac and Visual studio community. on login or register user I get the following message in Browser console

Error: System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (61): Connection refused

**Comment by CuriousDrive** [comment]
Is your Web API running when you try to login into Book Stores?

**Comment by stepro71** [comment]
It seems that I have a problem with database, I will investigate this...

**Comment by CuriousDrive** [comment]
Ok. I am gonna close this issue.

**Comment by CuriousDrive** [comment]
Ok. I am gonna close this issue.
