### ISSUE TITLE
Error: The circuit failed to initialize

### ISSUE THREAD

**Issue by TomasGuagnini** [CuriousDrive/BookStores#5]
When I run the APP it does not load and the console shows this error, no more details just that. I cloned the project, run it and thats it

**Comment by yonghanlee** [comment]
1. appsetting.json - modify url
  "AppSettings": {
    "BookStoresBaseAddress": "https://localhost:44391/api/"
  },

2. Run And Debugging. 
// response.StatusCode : 400
var response = await _httpClient.SendAsync(requestMessage);

// so, returnedUser is null.
var returnedUser = await userService.LoginAsync(user);

Is there something missing?

**Comment by CuriousDrive** [comment]
Have you setup database and web api for your project?

**Comment by CuriousDrive** [comment]
I talked to Tomas and he was able to solve the issue

**Comment by rehman22** [comment]
How you solve this issue .. i also have same issue

**Comment by TomasGuagnini** [comment]
Hi! You need to install a nuget package, something about system.text, not at home right now but promess i will write back asap. Anyway if you find by system.text let me know

Tomas Guagnini

**Comment by SwamiGanesh** [comment]
Hi any update on this ,I am facing same issue.Can someone tell root cause for this issue.

**Comment by SwamiGanesh** [comment]
install System.Text.Json from Nuget packet manager,this solved the issue. Don't know the root cause.
